# Uncomment this line to define a global platform for your project
 
platform :ios, "6.0"

pod 'AFNetworking', '~> 1.3.3' #// '2.2.1' uses different architecture and design..

pod 'MagicalRecord'  #//MagicalRecord

