<?php
//api uri constants
define("DEVICE_TRACKER","/device-tracker");
define("RESET_USER_PIN","/reset-user-pin");
define("ADD_USER","/add-user");
define("DEVICE_TRANSFER","/device-transfer");
define("ADD_DEVICE_INFORMATION","/add-device-info");
define("LIST_DEVICE_DETAILS","/list-device-details");
define("LIST_DEVICE_DETAILS_USER","/list-device-details-user");
define("CHECK_USER_ROLE","/check-user-role");
define("LIST_DEVICE_TYPES","/list-device-types");
define("GET_DEVICE_INFORMATION","/get-device-info");
define("EDIT_DEVICE_INFORMATION","/edit-device-info");
define("GET_DEVICE_INFORMATION_WITH_TRACK","/get-device-info-track");
define("GET_ASSIGNED_DEVICE_LIST","/get-assigned-device-list");
define("CHANGE_USER_PIN","/change-user-pin");
define("GET_TRACKING_INFORMATION","/get-tracking-info");
define("SEND_VERIFICATION_PUSH","/send-verification-push");
define("ADD_COMMENT","/add-comment");
?>
